apiVersion: v1
kind: ConfigMap
metadata:
  name: zufeto-config
  namespace: zufeto
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://zufeto-db.xxxx.ap-south-1.rds.amazonaws.com:5432/zufeto"
  SPRING_DATASOURCE_USERNAME: "zufeto_admin"
